### ISSUE TITLE
Mod did not successfully filter out the specified log content

### ISSUE THREAD

**Issue by LynnGuo666** [AzureDoom/Log-Begone#2]
Looks like this mod is not working properly

My Mod Config
`
[logbegone]`

`phrases = ["Player is either on another team or not on any team. Cannot remove from team"]`

`regex = ["/Player is either on another team or not on any team. Cannot remove from team/g"]`

This should actually have the effect of clearing the logs below.But this is not cleared in the log file.

`[17:46:01] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'CMINP616'.
	at net.minecraft.class_269.method_1157(class_269.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11099(class_634.java:2154) ~[client-intermediary.jar:?]
	at net.minecraft.class_5900.method_34173(class_5900.java:129) ~[client-intermediary.jar:?]
	at net.minecraft.class_5900.method_11054(class_5900.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]`

Is this a problem with the mod, or is there something wrong with my filter format?
please help me with this problem, thanks!
Love this mod :)

**Comment by SiverDX** [comment]
My assumption would be that there is a new-line character after `Player is` since the entire stacktrace is one log message but formatted
